Active record order
ninech/ordy pull request #1
Opened 2018-12-21 14:45 UTC by radicm

# Feature
Currently we have existing ordering solution on `ninevirt` that we would like to export into gem that could be used across nine's platform

# Implementation
- Added `ActiveRecord` orm ordering logic module `Ordy::Orm::ActiveRecord::Orderable` 
- Added orderable types  `Ordy::Orm::ActiveRecord::Orderable::ByAssociation | ByColumn | BySpecified`
- Added action view helper `Ordy::Helpers::ActionView::OrderableLinkHelper`

# Steps to test

__Env preparation__

Run development environment
```shell
# position in gem dir
cd ordy

# build app
docker-compose build app

# run app and attach with bash 
docker-compose run app /bin/bash
```

Run tests
```shell
# install dependencies
bundle exec appraisal install

# run tests for rails 4 env 
bundle exec appraisal rails-4 rspec

# run tests for rails 5 env
bundle exec appraisal rails-5 rspec
```

__Rails app testing__

Add migrations
```rb
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.text :name
      t.text :email
      t.text :state
      t.timestamps
    end
  end
end

class CreateComments < ActiveRecord::Migration[5.2]
  def change
    create_table :comments do |t|
      t.integer :content
      t.integer :user_id
      t.timestamps
    end
  end
end
```
Add to User model
```rb
class User < ApplicationRecord
  include Ordy::Orm::ActiveRecord::Orderable
  
  has_many :comments

  orderable_by do
    # order by field
    columns :name, :email
    
    # order by relations field
    associations comments: :scripts
    
    # sort by specified order
    specified(state: %w(new pendinguser migrating failed))
    
    # custom query
    query :users do |scope, args|
      scope.where(...).order(field: args[:direction])
    end
  end
end
```

Add to user helper
```rb
# users_helper.rb 
include Ordy::Helpers::ActionView::OrderableLinkHelper
```

Add to user index usage
```html
# index.html
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= order_link(User, 'email')%>
    <%= @users.each do|n|%>
    <tr> <%= n.as_json %></tr>
    <% end %>
  </tbody>
</table>

<br>
```

Add to `UsersController`
```rb
class UsersController
    def index
        if params[:order_by].present? && params[:direction].present?
          @users = User.order_by(params[:order_by] => params[:direction])
        else
          @users = User.all
        end
    end
end
```

Seed data
```rb
User.create(email: 'example@demo.com', name: 'user2', state: 'active')
User.create(email: 'deom@demo.com', name: 'user1', state: 'pending')
(1..5).each do |n| Comment.create(user_id: 1, content: n) end
(1..5).each do |n| Comment.create(user_id: 2, content: n) end
```

__Code testintg__
```
# order by columns
User.order_by(name: :asc)

# order by multiple columns
User.order_by(name: :asc, email: :desc) 
 
# order by association column
User.order_by(user: :asc)

# order by specified column values
User.order_by_specified(:state)

# order by custom query
User.order_by(custom_query: :asc)

# default ordering
User.order_by('') # same as User.order_by(nil)

# ordering by more than one criteria
User.order_by(email: :asc, state: :desc)
```

__View testing__

- Go to page where you added `<%= order_link('link_title', 'ordering_filed') %>`
- First time you get there url link should look like `http://localhost:3000/users`
- After first click url should change `http://localhost:3000/users?direction=asc&order_by=email` and data on view should change order
- After second click url should change `http://localhost:3000/users?direction=desc&order_by=email` and data on view should change order

2019-01-14 12:58 UTC, ghost requested changes

2019-01-14 12:58 UTC, ghost commented on lib/ordy/helpers/action_view/orderable_link_helper.rb
> +        DOWN_ICON = 'caret-down'
We shouldn't hardcode these values. They are all related to either Font Awesome or to our internal project(s).
Icon should be globally configurable, but we also need an option to customize it when needed. Maybe something like this:

```rb
# Configuration
Ordy.configure do |config|
  config.icon.down = 'caret-down'
  
  # ...
end

# Customization
order_link(User, 'email', icon: { down: 'caret-down' })
``` 
In addition, having a sane defaults (if nothing is configured) would be a plus.

2019-01-14 12:58 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +            def order_by(order_query = nil)
I would really like to include support for string params, like in original implementation. Also, I don't wan't to throw parsing into this method, so maybe something like `ParseQuery.new.call` would be a potential solution:

```rb
def order_by(order_query = nil)
  order_query = ParseParams.new.call(order_query) if order_query.is_a?(String)

  # ...
end
```

2019-01-14 12:58 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +              specs = order_query.symbolize_keys.each_with_object([]) do |(orderable, direction), result|
Maybe a `map` would be more concise (instead of `each_with_object`):

```rb
order_query.symbolize_keys.map do |orderable, direction|
  { orderable: orderable, direction: direction }
end
```

2019-01-14 12:58 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +              # binding.pry
:scissors:

2019-01-14 12:58 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +          def perform_ordering(scope, type, args: {})
Maybe I don't see it, but I'm not sure that this method is used anywhere... :confused:

2019-01-14 12:58 UTC, ghost commented on ordy.gemspec
> +  spec.authors     = ['RadicM']
```
s.authors     = ['nine.ch Development-Team']
s.email       = ['development@nine.ch']
s.homepage    = 'http://github.com/ninech/'
```

2019-01-14 12:58 UTC, aradunovic commented on spec/ordy/orm/active_record/orderable_spec.rb
> +describe Ordy::Orm::ActiveRecord::Orderable do
We also need the specs that check that current AR scope is not being overridden...for example, calling `#order_by` after some filtering:

```rb
User.where(status: :active).order_by(:last_name, :desc)
```

Also, we need to test default ordering

2019-01-16 11:44 UTC, radicm commented on lib/ordy/orm/active_record/orderable.rb
> +          def perform_ordering(scope, type, args: {})
There used to be idea that we use this as interface as for calling `orderable.call`

2019-01-22 10:57 UTC, ghost requested changes

2019-01-22 10:57 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +              if order_query.nil? || order_query.blank?
We can just do early return one  after another...branching is :nauseated_face: 

```rb
return default_order              if order_query.blank?
return default_order(order_query) if order_query.is_a?(Symbol)
```

2019-01-22 10:57 UTC, ghost commented on ordy.gemspec
> +  spec.description = 'Ordy simple sorting gem for RubyObject\'s and ORM\'s '
:scissors: `Ordy`

2019-01-22 10:57 UTC, ghost commented on ordy.gemspec
> +  spec.files       = ['lib/ordy.rb']
If I'm not wrong, these are the files that will be included into a gem package. Thus, all files should be specified here...

2019-01-22 10:57 UTC, ghost commented on spec/ordy/orm/active_record/orderable_spec.rb
> +        expect(User.order_by(name: :asc).pluck(:name)).to eq(%w(axample demo example))
Maybe we could use `let` here to specify different values for `order_by` argument:

```rb
let(:input) { { name: :asc } }
let(:result) { User.order_by(input).pluck(:name) }

# ...

expect(result).to eq(whatever)
```

2019-01-22 10:57 UTC, ghost commented on lib/ordy/orm/active_record/orderable.rb
> +              specs = if order_query.is_a?(String)
Would something like this be an improvement?
```rb
specs =  case order_query.is_a?(String)
         when String then parse_order_query(order_query)
         when Hash
          order_query.symbolize_keys.map do |(orderable, direction)|
            { orderable: orderable, direction: direction }
          end
         else
          nil
         end
```

2019-02-04 10:31 UTC, ghost requested changes

2019-02-04 10:31 UTC, aradunovic commented on readme.md
> +User.order_by(user: :asc)
This is not a valid example of ordering by association column. Keep the examples consistent.
In `Model` section you have `associations comments: :scripts`, so the example should be:

```rb
User.order_by(comments: :asc)
```

2019-02-04 10:31 UTC, aradunovic commented on readme.md
> +    specified(state: %w(new pendinguser migrating failed))
Maybe `new, pending, active, removed` would be better?

2019-02-04 10:31 UTC, aradunovic commented on readme.md
> +    associations comments: :scripts
Can ordering even work on `has_many` assoc like this?

2019-02-04 10:31 UTC, aradunovic commented on readme.md
> +    query :users do |scope, args|
It doesn't make much sense to order `User` by `:users`, don't you agree?
Also give some real example for `where` and `order` method arguments.

2019-02-04 10:31 UTC, aradunovic commented on spec/ordy/orm/active_record/orderable_spec.rb
> +        expect(User.order_by(name: :asc).pluck(:name)).to eq(%w(axample demo example))
:point_up: still waits from previous review...

2019-02-04 15:26 UTC, radicm commented on readme.md
> +    associations comments: :scripts
Yes

2019-03-12 12:54 UTC, orthodoX approved these changes
It looks ok now, let's roll with this 👍

2019-03-12 14:02 UTC, merged